kind: pipeline
name: main-pipeline

platform:
    os: linux
    arch: amd64

steps:
- name: test
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - go test -cover ./dkgnode ./logging ./pvss ./common ./tmabci
  - cd ./dkgnode
  - go build
