kind: pipeline
name: main-pipeline

platform:
    os: linux
    arch: amd64

steps:
- name: test
  image: overmorrow/torus-builder:1.12
  volumes:
  - name: deps
    path: /go
  commands:
  - go test -cover ./dkgnode ./logging ./pvss ./common ./tmabci -mod=vendor
  - cd ./dkgnode
  - go build -mod=vendor
