kind: pipeline
name: main-pipeline

platform:
    os: linux
    arch: amd64

steps:
- name: test-build-n-publish  
  image: plugins/ecr
  environment:
    GOPROXY: https://goproxy.io
  settings:
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    repo: torus/torus-public
    registry: 703476792259.dkr.ecr.ap-southeast-1.amazonaws.com
    region: ap-southeast-1
    tags:
      - latest
