version: '3'

services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    command: -s=something
    networks:
      localnet:

  node_one:
    image: torus:latest
    ports:
      - "26657-26658:26656-26657"
      - "1080"
      - "7001:8080"
      - "8000:8000"
    volumes:
      - ./config/config.local.1.json:/.torus/config.json
      - ./tests/openssl:/.torus/openssl
    links:
      - ganache
    networks:
      localnet:
        ipv4_address: 192.167.10.2
  node_two:
    image: torus:latest
    ports:
      - "1080"
      - "26659-26660:26656-26657"
      - "7002:8080"
      - "8001:8001"
    volumes:
      - ./config/config.local.2.json:/.torus/config.json
      - ./tests/openssl:/.torus/openssl
    links:
      - ganache
    networks:
      localnet:
        ipv4_address: 192.167.10.3

  node_three:
    image: torus:latest
    ports:
      - "1080"
      - "26661-26662:26656-26657"
      - "7003:8080"
      - "8002:8002"
    volumes:
      - ./tests/openssl:/.torus/openssl
      - ./config/config.local.3.json:/.torus/config.json
    links:
      - ganache
    networks:
      localnet:
        ipv4_address: 192.167.10.4
  node_four:
    image: torus:latest
    ports:
      - "1080"
      - "26663-26664:26656-26657"
      - "7004:8080"
      - "8003:8003"
    volumes:
      - ./config/config.local.4.json:/.torus/config.json
      - ./tests/openssl:/.torus/openssl
    links:
      - ganache
    networks:
      localnet:
        ipv4_address: 192.167.10.5
  node_five:
    image: torus:latest
    ports:
      - "1080"
      - "26665-26666:26656-26657"
      - "7005:8080"
      - "8004:8004"
    volumes:
      - ./config/config.local.5.json:/.torus/config.json
      - ./tests/openssl:/.torus/openssl
    links:
      - ganache
    networks:
      localnet:
        ipv4_address: 192.167.10.6

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/16
