version: '3'

services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    entrypoint:
      - node
      - ./build/cli.node.js
      - --deterministic
      - --networkId
      - '5777'
      - --hostname
      - '0.0.0.0'
      - --debug
  node_one:
    build: 
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./config/config.local.1.json:/.torus/config.json
    links:
      - ganache
  node_two:
    build: 
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./config/config.local.2.json:/.torus/config.json
    links:
      - ganache
  node_three:
    build: 
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./config/config.local.3.json:/.torus/config.json
    links:
      - ganache
  node_four:
    build: 
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./config/config.local.4.json:/.torus/config.json
    links:
      - ganache
  node_five:
    build: 
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./config/config.local.5.json:/.torus/config.json
    links:
      - ganache
