version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@3.1.0
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          create-repo: true
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: AWS_DEFAULT_REGION
          tag: "${CIRCLE_SHA1}"
